{% set version = "1.22.0" %}

package:
  name: numbat
  version: {{ version }}

source:
  url: https://github.com/sharkdp/numbat/archive/v{{ version }}.tar.gz
  sha256: db5d9c2c0ec113f6773c22e7c09c51c08a62a196ca28a2008ff11546c77297bb

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - numbat --help

about:
  home: https://numbat.dev/
  dev_url: https://github.com/sharkdp/numbat
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: A statically typed programming language for scientific computations

extra:
  recipe-maintainers:
    - apcamargo
