{% set version = "1.20.0" %}

package:
  name: numbat
  version: {{ version }}

source:
  url: https://github.com/sharkdp/numbat/archive/v{{ version }}.tar.gz
  sha256: 8b368bafe05eb25f776e516abd94c3a4899b32e520934b6cb4d123ec03f1e9dc

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - numbat --help

about:
  home: https://numbat.dev/
  dev_url: https://github.com/sharkdp/numbat
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: A statically typed programming language for scientific computations

extra:
  recipe-maintainers:
    - apcamargo
